// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SweetPlayer.Core.Data;

#nullable disable

namespace SweetPlayer.Core.Migrations
{
    [DbContext(typeof(SweetPlayerDbContext))]
    partial class SweetPlayerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("SweetPlayer.Core.Models.MediaSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebDavUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebDavPasswordEncrypted")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path");

                    b.ToTable("MediaSources");
                });

            modelBuilder.Entity("SweetPlayer.Core.Models.MovieMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackdropLocalPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cast")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChineseTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<string>("DoubanId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DoubanRating")
                        .HasColumnType("REAL");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterLocalPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeasonsEpisodeCount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Synopsis")
                        .HasColumnType("TEXT");

                    b.Property<string>("TmdbId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalSeasons")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DoubanId");

                    b.HasIndex("ChineseTitle", "Year");

                    b.ToTable("MovieMetadata");
                });

            modelBuilder.Entity("SweetPlayer.Core.Models.PlaybackProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastPlayed")
                        .HasColumnType("TEXT");

                    b.Property<double>("PositionSeconds")
                        .HasColumnType("REAL");

                    b.Property<int>("VideoFileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VideoFileId")
                        .IsUnique();

                    b.ToTable("PlaybackProgress");
                });

            modelBuilder.Entity("SweetPlayer.Core.Models.VideoFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EditionTag")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Episode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EpisodeTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("HasDolbyAtmos")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasDolbyVision")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasHdr10")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MovieMetadataId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Season")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FullPath")
                        .IsUnique();

                    b.HasIndex("MediaSourceId");

                    b.HasIndex("MovieMetadataId");

                    b.ToTable("VideoFiles");
                });

            modelBuilder.Entity("SweetPlayer.Core.Models.VideoFile", b =>
                {
                    b.HasOne("SweetPlayer.Core.Models.MediaSource", "MediaSource")
                        .WithMany("VideoFiles")
                        .HasForeignKey("MediaSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SweetPlayer.Core.Models.MovieMetadata", "MovieMetadata")
                        .WithMany("VideoFiles")
                        .HasForeignKey("MovieMetadataId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MediaSource");

                    b.Navigation("MovieMetadata");
                });

            modelBuilder.Entity("SweetPlayer.Core.Models.PlaybackProgress", b =>
                {
                    b.HasOne("SweetPlayer.Core.Models.VideoFile", "VideoFile")
                        .WithMany()
                        .HasForeignKey("VideoFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoFile");
                });

            modelBuilder.Entity("SweetPlayer.Core.Models.MediaSource", b =>
                {
                    b.Navigation("VideoFiles");
                });

            modelBuilder.Entity("SweetPlayer.Core.Models.MovieMetadata", b =>
                {
                    b.Navigation("VideoFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
